### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by browhattheheck1** [oxters168/UnitySourceEngine#1]
added this with the other required library to my unity 2019.2.9 projects asset folder, I get 3 errors:

Assets\UnityHelpers-master\Helpers\MeshHelpers.cs(5,7): error CS0246: The type or namespace name 'g3' could not be found (are you missing a using directive or an assembly reference?)

Assets\UnityHelpers-master\Helpers\MeshHelpers.cs(600,24): error CS0246: The type or namespace name 'DMesh3' could not be found (are you missing a using directive or an assembly reference?)

Assets\UnityHelpers-master\Helpers\MeshHelpers.cs(833,29): error CS0246: The type or namespace name 'DMesh3' could not be found (are you missing a using directive or an assembly reference?)

**Comment by oxters168** [comment]
Sorry for the late reply. When using this repository, please make sure to include the [UnityHelpers](https://github.com/oxters168/UnityHelpers) repository with its submodules. If you don't know how to include the submodules when pulling from git, you can use [this guide](https://git-scm.com/book/en/v2/Git-Tools-Submodules). If you're not pulling from git but instead downloading the zip, then you'll need to manually download [g3](https://github.com/gradientspace/geometry3Sharp) and place it in your assets folder. If UnityHelpers has any other submodules, you'll need to do the same for those. But I believe it only has the one. Good luck!

**Comment by oxters168** [comment]
Closed due to inactivity
